= Round 10 Answers

== Odd Man Out

Pick the thing that does not belong

Possible Points: 10

Time: 10 min.

1) Which is not a greek goddess?

a. Aphrodite
b. Athena
c. *Venus*
d. Nike

2) Which company cannot trace it's history back to Bell Systems? 

a. *T-Mobile*
b. AT&T
c. Verizon
d. CenturyLink


3) Which actor was not in the movie Dodgeball?

a. Ben Stiller
b. *Owen Wilson*
c. Vince Vaughn
d. Justin Long

4) Which company does not make printers?

a. Dell
b. Canon
c. *Lenovo*
d. HP

5) Which country has not invaded Poland?

a. Italy
b. *Spain*
c. Germany
d. Russia


Ok, Jeopardy Style - Why is the highlighted person, place, or thing the odd one out. We will accept your answer if it makes sense and it is not terrible.

6) Miley Cyrus, *Ariana Grande*, Demi Lovato, Selena Gomez *Ariana Grande got her start on Nikelodeon, the rest started on Disney Channel*

7) Beryllium, Sodium, Zinc, *Iodine* *Iodine is part of the Non-Metals group on the periodic table, the rest are considered Metals*

8) John F Kennedy, Ulysses S. Grant, *Millard Fillmore*, James K. Polk *Millard Fillmore was not a member of our 2 parties that exist today, he was a Whig*

9) *Vision*, Iron Man, Spiderman, Hulk *Vision was one of the few Marvel Characters that were not in Avengers: Endgame, the rest were in the movie*

10) Chinook, *Persian*, Pumi, Cane Corso *Persian is a breed of cats, the rest are breeds of dogs*

link:../../../index.html[Click here to return to the main site]
