== Round 4 Answers

Halloween

Possible Points: 10

Time: 10 min.

1. Based on the cumulative worldwide box office, what is the highest grossing horror film of all time? *It, 2017*

2. In 2019, what were the most popular kids costumes for 
    girls? *Princess, specifically Elsa and Ana*
    boys? *Superhero, specifically Spiderman*

3. In what country was the first written account of children using the phrase “trick or treat” on Halloween? *Canada*

4. The farmer who currently holds the Guiness World Record title for 'World's Heaviest Pumpkin' is from what country? *Belgium*

5. According to gardner.com, in days, How long does it take to grow a pumpkin? (experts give a 10 day time span - we will consider all answers within the span correct. For example: if the estimate is 0-10 days we will accept 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 as right. Pro-tip, it is NOT 0-10) *90-100 days*

6. The original Jack-O-Lanterns were not pumpkins, what vegetable were they? *Turnips*

7. In 2004, Hollywood passed a city ordinance banning the use and sale of what product from 12:01am October 31st to 12:00pm on November 1st? *Silly String*

8. In 'It's the Great Pumpkin Charlie Brown' what game do the kids play at the Halloween party? *Bobbing for Apples*

9. Name as many candies as you can. The team with the most will win this point. *A lot*
