= Seaweed is cool, Seaweed is fun. Seaweed gets its food from the rays of the sun! = 10 Minutes; 16 points

1) What percentage of the ocean is explored? (+/- 1%)

- 5%

2) What is it called when corals turn white due to temperature change?

- Coral bleaching

3) Which African country is leading in the most concentrated solar power farm?

- Morocco

4) What percentage of heat trapped in the atmosphere goes back into the ocean? (+/- 1%)

- 93%

5) In 1973, the Endangered Species Act was passed to protect a number of species. Which species was at the top of that list at the time?

- Blue Whale

6) James Cameron dove to the deepest part of the ocean almost 7 miles down in his custom built man-driven submarine. What was the name of said sub?

- Challenger; Deepsea Challenger

7) Since 2016, the Great Barrier Reef has lost more than 50% of what species?

- The Coral

8) How many trees are cut down yearly? (+/- 1 billion)

- 15 billion

9) What is the term for specific areas in the ocean where no one can fish. temperature stays rough;y the same, and is equivalent to conservation areas but in water?

- Hope Spots

10) Very famous oceanographer who broke through a gender gab and led five other women on the Tektite II mission. What is her name?

Sylvia Earle

11) Match the celebrities to the foundation they've founded to support the environment

a) Matt Damon - water.org
b) Brad Pitt - Make It Right Foundation
c) Robert Redford - Sundance Preserve
d) Jane Fonda - Fire Drift Friday's
e) David Attenborough - World Land Trust
f) Meryl Streep - Mother's and Others


link:../index.html[Click here to return to the main site]