= Seaweed is cool, Seaweed is fun. Seaweed gets its food from the rays of the sun! = 10 Minutes; 16 points

1) What percentage of the ocean is explored? (+/- 1%)

2) What is it called when corals turn white due to temperature change?

3) Which African country is leading in the most concentrated solar power farm?

4) What percentage of heat trapped in the atmosphere goes back into the ocean? (+/- 1%)

5) In 1973, the Endangered Species Act was passed to protect a number of species. Which species was at the top of that list at the time?

6) James Cameron dove to the deepest part of the ocean almost 7 miles down in his custom built man-driven submarine. What was the name of said sub?

7) Since 2016, the Great Barrier Reef has lost more than 50% of what species?

8) How many trees are cut down yearly? (+/- 1 billion)

9) What is the term for specific areas in the ocean where no one can fish. temperature stays rough;y the same, and is equivalent to conservation areas but in water?

10) Very famous oceanographer who broke through a gender gab and led five other women on the Tektite II mission. What is her name?

11) Match the celebrities to the foundation they've founded to support the environment

a) Matt Damon
b) Brad Pitt
c) Robert Redford
d) Jane Fonda
e) David Attenborough
f) Meryl Streep

i) World Land Trust
ii) Mother's and Others
iii) Make It Right Foundation 
iv) Fire Drift Friday's
v) Sundance Preserve
vi) water.org

link:../index.html[Click here to return to the main site]