= Monarchies are so 1775 - Answers

== Answer the following questions that all have something to do with royalty (or royal titles).

1) What was King George VI (Queen Elizabeth II's Father) given name at birth?

*Albert*

2) In the Super Mario franchise who is the love interest of Luigi? 

*Princess Daisy*

3) What country currently has the richest monarchy in the world? 

*Thailand* 

4) In the version of Hamilton now streaming on Disney+, who is the actor that plays King George? 

*Jonathan Groff*

5) Who is the main antagonist of the 2001 animated feature film Shrek? 

*Lord Farquaad*

6) In the new Netflix original series Brigerton, what is the royal title of the main character Simon Basset? 

*Duke (of Hastings)*

7) Who is the current heir to the throne of England? 

*Prince Charles* 

8) How many wives did King Henry the 8th have in his lifetime? 

*6*

9) What Disney animated movie was partially based on the short story "Happy Dan the Whistling Dog" by Ward Greene?

*Lady and the Tramp*

10) This title belongs to a 1990 crime movie, an animated lion, and a song on the soundtrack to Newsies. 

*King of New York*

'''

link:../../../index.html[Click here to return to the main site]