= Playing the Long Game

== Possible Points = 10

=== Answer the following questions about the longest, the largest, or the oldest things.


1) Who has the most number 1 billboard hits of all time?

2) In miles, what is the longest distance ever swum without flippers in open sea? +/- 5 miles


3) Who is the oldest quarterback in the NFL right now?


4) The _ is considred the longest day of the year (the most sunlight) for the Northern Hemisphere.


5) Louis the Great is the longest reigning monarch of all time at 72 years and 110 days. What country did he reign over?


6) The Simpsons hold the record for the longest running television show of all time, what holds the record for the longest-running *live-action comedy* series in television history?

(*HINT:* Question 7 and 8 are not the same country)

7) What country has the highest median age in the world?


8) What country has the highest percentage of people over 65 years?


9) According to the Guiness book of world records, the longest animal is held by what species?


10) What song holds the record for the longest stretch at No. 1 with 19 weeks?
