= Playing the Long Game - Answers


1) Who has the most number 1 billboard hits of all time?

*The Beatles*

2) In miles, what is the longest distance ever swum without flippers in open sea? +/- 10 miles

*139.8*

3) Who is the oldest quarterback in the NFL right now?

*Tom Brady*

4) The _ is considered the longest day of the year (the most sunlight) for the Northern Hemisphere.

*June/Summer Solstice*

5) Louis the Great is the longest reigning monarch of all time at 72 years and 110 days. What country did he reign over?

*France*

6) The Simpsons hold the record for the longest running television show of all time, what holds the record for the longest-running *live-action comedy* series in television history?

*It's Always Sunny in Philadelphia*

7) What country has the highest median age in the world?

*Monoco*

8) What country has the highest percentage of people over 65 years old?

*Japan*

9) According to the _Guiness Book of World Records_, the longest animal is held by what species?

*a worm*

10) What song holds the record for the longest stretch at No. 1 with 19 weeks?

*Lil Nas X's "Old Town Road," featuring Billy Ray Cyrus*
