=== Kame Hame Haaa! = 15 Minutes; 22 Points

1) What are the 4 shows that are a big part of the "Big 4" of Anime? (1 point for each correct answer)

BONUS: Who is the leading protagonist of each show (1 point for each correct answer; doesn't need full name)

2) What was the most popular magazine is exclusive to anime and manga (in the world)?

3) _____ is the genre that is exclusive to anime and manga.

BONUS: Who is the target audience of this genre?

4) How many episode (subbed) of One Piece are there as of today (+/- 40)

5) Which popular anime got a reboot that ended up being more popular that the original (hint: reboot has "brotherhood" added to it)

6) Which anime was regarded as the one that kickstarted the wave of "isekai" anime in the 2010's? (This anime is also regarded as trash due to its lack of characted personality and wide array of plot holes)

 a) Toradora!
 b) Sword Art Online
 c) Overlord
 d) One Punch Man
 e) Re: Zero

7) Which of the following platforms ONLY streams anime?

 a) Netflix
 b) Hulu
 c) VRV
 d) Crunchyroll

8) There is an abbreviated term in anime to describe a fantasy gae where people are able to play with thousands of others in virtual reality. What is that abbreviation (8 letters, including VR)(1 point for each letter in the correct space)

V R  --  --  --  --  --  --

9) What is the most famous stule of Japanese sword both in anime and in real life?


link:../index.html[Click here to return to the main site]