= Frankly My Dear, I Don't Give a Damn = 10 Minutes; 15 Points

=== The answers to the following are the last words of famous people, movie characters, books, and songs. (I'm quoting this verbatum from Rupie): If person, name person. If character, name character (not movie). If book, name book. If song, name song (not artist). Bonus point if you can name: Movie titles

1) "Friends applaud, the comedy is over." *Famous Person*

2) "I'm losing it." *Famous Person*

3) "Swing low, sweet chariot." *Famous Person*

4) "FREEDOOOOOOOOM!" *Character*

5) "Never go in against a Sicilian when death is on the line. Hahahaha!" *Character*

6) "Rosebud." *Character*

7) "So long partner." *Character*

8) "I'll be right here." *Character*

9) "I would have followed you, my brother... my captain... my king." *Character*

10) "I have been and always shall be your friend... Live long and prosper." *Character*

11) "Loves such an old fashioned word and love dares you to care for the people on the edge of the night and love dares you to change our way of caring about ourselves, this is our last dance, this is our last dance." *Song*

12) "So for once in my life, let me get what I want/Lord knows it would be the first time." *Song*

13) "Grow old with me, let us share what we see, and oh the best it could be, just you and I" *Song*

14) "All was well" *Book*

15) "Slowly, very slowly, like tow unhurried compass needles, the feet turned towards the right; north, north-east, east, south-east, south, south-south-west; the paused, and, after a few seconds, turned as unhurriedly back towards the left. South-south-west, south, south-east, east..." *Book*

