= Sweet Treats - Answers

Possible Points: 10

Time: 10 mins

1. A roux is a cooking mixture of equal parts _ and _ ? *Flour and fat/butter*

2. A souffe is a baked egg-based dish originating in what country? *France*

3. What do you make by mixing finely ground almonds with sugar, corn syrup and egg whites? *Marzipan*

4. What could happen to your cake batter if you add eggs that are too cold? *Curdle*

5. This biscuit know for being inexpensive and long lasting was a standard ration for many militaries and navies throughout the 17th, 18th, and 19th centuries. *Hardtack*

6. Cream of tartar is a bi-product of what? *wine*

7. Where did the German Chocolate cake originate? *Texas, USA*

8. In a recipe for Irish soda bread what ingredient is used for leavening? *Baking soda*

9. Currently, 4 countries in the world provide free school lunches for all children regardless of a family's ability to pay, name one. *Sweden, Finland, India, Estonia*

10. What are the 3 type of meringue? *Italian, French, and Swiss*
