= It's Stil Rock and Roll to Me

=== Answer these questions about classic rock songs (1/2 point for each) = 20 Minutes; 10 Points



1) What was the old man drinking in Billy Joel's "Piano Man"?

2) How Many women does he have on his mind in the Eagles' "Take it Easy"?

3) If your mind is feeling fine, what can you smell on Aliotta Haynes & Jerremiah's "Lake Shore Drive"?

4) What do the lyrics "toora-loora-toora-loo-rye-ay" mean in Dexy's Midnight Runners' "Come on Eileen"?

- BONUS: What does "too-rye-aye" mean (no point just for fun)

5) Why is Mars not a good place to raise your kids in Elton John's "Rocket Man"?

6) What can be seen in her eyes in Guns n' Roses' "November Rain"?

7) What is the lady sure of in the beginning of Led Zeppelin's "Stairway to Heaven"?

8) Where was the city boy born and raised in Journey's "Don't Stop Believing"?

9) Who were the popular steadies in Billy Joel's "Scenes from an Italian Resturant"?

10) Where were the two lost souls swimming in Pink Floyd's "Wish You Were Here"?

11) What is the first thing Steve Miller is referred to as in "The Joker"?

12) What only happens when it's raining in Fleetwood Mac's "Dreams"?

13) What words did Kurt Cobain deem rhymable in the chorus of Nirvana's "Smells Like Teen Spirit"?

14) Where is Styx setting sail for in "Come Sail Away"?

15) What was such an easy game to play in The Beatle's "Yesterday"?

16) Who were out in the streets in Elton John's "Tiny Dancer"?

17) What color are the curtains in Cream's "White Room"

18) What has Layla been doing for "much too long" in Eric Clapton's (or Derek and the Dominos') "Layla" (three words)?

19) What soaks a callous heart in Alice In Chains' "I Stay Away"?

20) What's "creepin' in" in Tom Petty and the Heartbreakers' "Mary Jane's Last Dance"?

