= 2020

== Possible Points = 10

=== Answer these questions about the unusal year we all had in 2020.


1) Who was the first major political world leader to contract Covid-19? 


2) What is the real name of the Tiger King?


3) Which foreign language movie was the first to win the Academy Award for Best Motion Picture?


4) Elon Musk has a son with which singer?


5) March 31st, 2020 marked the end of the most devastating bushfire season ever recorded in what country?


6) The Democratic Party held a presidential primary debate over two days in Miami, Florida, on June 26-27, 2019. It was the first of 11 Democratic primary debates that took place during the 2020 presidential election. How many people qualified for this debate?


7) Baby Yoda was introduced to the world in the Disney+ original series The Madalorian. What is his real name?


8) On January 6, 2020 Peter Weber appreared on ABC as The Bachelor for the shows 24th season. What is his profession?


9) Who performed the 2020 superbowl halftime show?


10) According to Forbes, which entrepreneur became the first person in history to have a net worth of more than 200 billion?


'''

link:../../../index.html[Click here to return to the main site]