= 2020 - Answers


1) Who was the first major political world leader to contract Covid-19? 

*Boris Johnson*

2) What is the real name of the Tiger King?

*Joe Exotic*

3) Which foreign language movie was the first to win the Academy Award for Best Motion Picture?

*Parasite*

4) Elon Musk has a son with which singer?

*Grimes*

5) March 31st, 2020 marked the end of the most devastating bushfire season ever recorded in what country?

*Australia*

6) The Democratic Party held a presidential primary debate over two days in Miami, Florida, on June 26-27, 2019. It was the first of 11 Democratic primary debates that took place during the 2020 presidential election. How many people qualified for this debate?

*20*

7) Baby Yoda was introduced to the world in the Disney+ original series The Madalorian. What is his real name?

*Grogu*

8) On January 6, 2020 Peter Weber appreared on ABC as The Bachelor for the shows 24th season. What is his profession?

*Delta airlines Pilot*

9) Who performed the 2020 superbowl halftime show?

*Jennifer Lopez and Shakira*

10) According to Forbes, which entrepreneur became the first person in history to have a net worth of more than 200 billion?

*Jeff Bezos*


'''

link:../../../index.html[Click here to return to the main site]
