= Scandalous - Answers

Possible Points: 10

Time: 10 mins

1. The Tea Pot Dome Scandal was the most notorious example of corruption in American history pre-watergate. Which president is associated with this scandal? *Warren G Harding*

2. What would the evening of October 20, 1973 become known as due to a series of shocking orders given by Richard Nixon during the Watergate Scandal? *SAturday Nigh Massacre*

3. Andrew Jackson appointed John Eaton as his secretary of war and so began the Eaton Scandal that would eventually lead to all but on cabinet member resigning. Why? *Eaton married Peggy, a widower plagued with illicit activity not appoved of by the social elites wives*

4. What US Senator resigned in 2018 after serveral allegations of sexual misconduct were made against him? *Al Franken*

5. While attending a banquet hosted by the Prime Minister of Japan, Kiichi Miyazawa, U.S. President George H. W. Bush had some news worthy behavior, what happened? *He fainted after vomiting in Miyazawa's lap*

6. Who was the presumed Democratic presidential candidate in the spring of 1987 when the Miami Herald reported that rumors of his “womanizing” were true? *Gary Hart*

7. Which former president is it rumored that he had an illegitimate son with a widow, Maria Halpin, in 1874? *Grover Cleveland*

8. This term was made popular in the 2000 Bush-Gore election for the incorrectly punched voting cards. *Hanging Chad*

9. President Barack Obama held a live press conference on increasing the military response against the Islamic State (ISIS) on August 28, 2014. What about his appearance led to media and social media criticism? *He was wearing a tan suit*

10. Before becoming President (because after there are just too many scandals to choose from) how many times had companies owned by Donald Trump filed for bankrupcy? *6*