= Break a Leg! 10 Minutes, 25 Points

1) What "Newsies" song features the lyrics: "Tomorrow they may wrap fishes in it, but I was a star for one whole minute!"?

- King of New York

2) What show features the lyrics: "No more talk of darkness, Forget these wide-eyed fears, I'm here, nothing can harm you, my words will warm and calm you, Let me be your freedom, let daylight dry your tears.."? Name the song for a bonus point!

- Phantom of the Opera
- Angel of Music

3) In the song "Prince Ali" from "Aladdin," how many monkeys are mentioned?

- 95 White Persian Monkeys

4) In "The Producers," what's bad luck to say on opening night?

- Good Luck

5) In “West Side Story,” Riff and Tony repeat an oath of loyalty to each other: Riff says "womb to tomb" what does Tony respond?

- "Birth to Earth"

6) Hamilton has the highest words per minute average for any musical. The next closest musical is “Spring Awakening” with an average of 77wpm. Hamilton has a runtime of 2 hours and 23min. What is the average words per minute throughout the musical, “Hamilton”?

- 144 words per minute, 20,520 words total

7) Name as many characters from the roll call in “The Nicest Kids in Town” from “Hairspray” (18 total) (-1 point for each name you get wrong)

- “I’m Amber! Brad! Tammy! Fender! Brenda! Sketch! Shelley! I.Q.! Lou Ann! Joey! Mickey! Becky! Jesse! Carla! Polly! Maureen! Doreen! And I'm...Link!”

9) Finish the lyric: “Raindrops on roses / And whiskers on kittens / ___ ___ ___ and warm woolen mittens
 
- a) Bright copper kettles

10) What famour ballet dancer is featured in multiple musical numbers in Singin' in the Rain?

- Cyd Charrise

11) What do 'the colors of the world' mean to either Marius or Enjolras in the song "ABC Cafe / Red & Black" Le Miserable. Hint: must have two answers for each; the colors are red and black (4 answers per person, 8 possible points total).

- Red - the blood of angry men / a world about to dawn / I feel my soul on fire / is the color of desire
- Black - the dark of ages past / the night that ends at last / my world I'd she's not there / is the color of despair


