= Break a Leg! 10 Minutes, 25 Points

1) What "Newsies" song features the lyrics: "Tomorrow they may wrap fishes in it, but I was a star for one whole minute!"?

2) What show features the lyrics: "No more talk of darkness, Forget these wide-eyed fears, I'm here, nothing can harm you, my words will warm and calm you, Let me be your freedom, let daylight dry your tears.."? Name the song for a bonus point!

3) In the song "Prince Ali" from "Aladdin," how many monkeys are mentioned?

4) In "The Producers," what's bad luck to say on opening night?

5) In “West Side Story,” Riff and Tony repeat an oath of loyalty to each other: Riff says "womb to tomb" what does Tony respond?

6) Hamilton has the highest words per minute average for any musical. The next closest musical is “Spring Awakening” with an average of 77wpm. Hamilton has a runtime of 2 hours and 23min. What is the average words per minute throughout the musical, “Hamilton”?

7) Name as many characters from the roll call in “The Nicest Kids in Town” from “Hairspray” (18 total) (-1 point for each name you get wrong)

9) Finish the lyric: “Raindrops on roses / And whiskers on kittens / ___ ___ ___ and warm woolen mittens
 
 a) Bright copper kettles
 b) Book of mormon
 c) Moulin rouge
 d) Wicked
 e) Singing in the rain
 f) Chicago 
 g) Billy Elliot 

10) What famour ballet dancer is featured in multiple musical numbers in Singin' in the Rain?

11) What do 'the colors of the world' mean to either Marius or Enjolras in the song "ABC Cafe / Red & Black" Le Miserable. Hint: must have two answers for each; the colors are red and black (4 answers per person, 8 possible points total).

link:../index.html[Click here to return to the main site]