= Reality Check - Round 7

Possible Points: 14

Time: 10 min.

1) The reality show, Survivor, has been on for a whopping 40 seasons, all of which have been hosted by the same person. Name the host. (must be first and last)

2) The Roloff family, stars of TLC’s Little People, Big World, own what kind of business located near Portland, Oregon?

3) Bravo’s The Real Housewives franchise follows (or has followed) the lives of well-to-do women in all of the following cities except for:
    a. Potomac
    b. Salt Lake City        
    c. Chicago
    d. D.C.

4) Mike Rowe, host of Dirty Jobs, is the narrator for which reality TV series that follows individuals on their search for opies?

5) True or False: Villa de la Vina, aka the Bachelor/Bachelorette mansion, is the actual home of the show’s host, Chris Harrison.

6) Jim Bob and Michelle Duggar’s show, 19 Kids and Counting on TLC, chronicled the daily lives of this strict Baptist family. How many boys and how many girls (children only) are in the family? (Hint: boys + girls = 19 children)

*Bonus!* Name all of the boys

*Bonus!* Name all of the girls

7) The host of CBS’s Big Brother, has been married to a major network CEO since 2004. She only recently began using both her maiden name and married name when signing off. Name the host and her husband.

8) The first reality show, An American Family, aired in what year on PBS and followed the Loud family that lived in Santa Barbara? (credit for +/- 2 years)

9) What reality show aired from 1992-2017 and used the following in the opening credits for most of the seasons?
“This is the true story…of seven strangers…picked to live in a house…(work together) and have their lives taped…”

10) The queens of reality television, the Kardashians, will be ending their reality show, Keeping Up with the Kardashians, after the next season. How many total seasons has the show been on?

link:../../../index.html[Click here to return to the main site]
