= Who am I - Round 5

Possible Points: 10

Time: 10 min.

Name the famous person/character/group/thing/etc. (real or fictional) by the vague description.

1) I am an ex peanut farmer who has spent much of my later years on humanitarian causes including fighting malaria and building homes in lower income areas.

2) Often impulsive and short-tempered, I am a bronto crane operator who met my wife while previously working as a bellhop.

3) I am the first American woman to officially be ranked a billionaire.

4) I was born in Atlanta, Georgia in 1978, and though I am an SNL Star now I am not known for my first film, D2: The Mighty Ducks.

5) The Guinness Book of World Records created an all-new category just for us, titled the highest paid single appearance of a band.

6) In 1985, as a member of Twisted Sister I testified in front of congress in a historical case about music censorship.

7) After making the cover of TIME Magazine on December 31st, 1990, I have continued my role as a skateboarding kid on one of the longest running TV shows still today.

8) I am known as a 1970s football star who has been inducted into the College Football Hall of Fame, the Pro Football Hall of Fame, and I starred in the movie Failure to Launch.

9) I am an attentive resturant owner who spends my days counting my money in the back office while protecting the secret formula from the failed burger joint owner accross the street.

10) I am considered one of the best-selling music artists of all time, I was inducted into the hip hop hall of fame, and also released 5 albums which all went platinum in the United States - all of which happened after my untimely death in 1996.
