= NOT IT! - Round 10

Possible Points: 10

Time: 10 min.

1) Which is NOT a greek goddess?

a. Aphrodite
b. Athena
c. Venus
d. Nike

2) Which company canNOT trace it's history back to Bell Systems? 

a. T-Mobile
b. AT&T
c. Verizon
d. CenturyLink


3) Which actor was NOT in the movie Dodgeball?

a. Ben Stiller
b. Owen Wilson
c. Vince Vaughn
d. Justin Long

4) Which company does NOT make printers?

a. Dell
b. Canon
c. Lenovo
d. HP

5) Which country has NOT invaded Poland?

a. Italy
b. Spain
c. Germany
d. Russia


6) Which actress did NOT start on Disney Channel?

a. Miley Cyrus
b. Ariana Grande
c. Demi Lovato
d. Selena Gomez

7) Which element is NOT in the Metal group of elements on the periodic table?

a. Beryllium
b. Sodium
c. Zinc
d. Carbon

8) Which US President was NOT a member of one of the 2 political parties that exist today?

a. Ulysses S. Grant
b. Millard Fillmore
c. James K. Polk
d. John F Kennedy

9) Which Marvel Character did NOT appear in Avengers: Endgame?

a. Vision
b. Iron Man
c. Spiderman
d. Rocket

10) Which of these breeds is NOT a dog breed?

a. Chinook
b. Persian
c. Pumi
d. Cane Corso

link:../../../index.html[Click here to return to the main site]
