= Odd Man Out - Round 10

Pick the thing that does not belong

Possible Points: 10

Time: 10 min.

1) Which is NOT a greek goddess?

a. Aphrodite
b. Athena
c. Venus
d. Nike

2) Which company CANNOT trace it's history back to Bell Systems? 

a. T-Mobile
b. AT&T
c. Verizon
d. CenturyLink


3) Which actor was NOT in the movie Dodgeball?

a. Ben Stiller
b. Owen Wilson
c. Vince Vaughn
d. Justin Long

4) Which company does NOT make printers?

a. Dell
b. Canon
c. Lenovo
d. HP

5) Which country has NOT invaded Poland?

a. Italy
b. Spain
c. Germany
d. Russia


Ok, Jeopardy Style - Why is the highlighted person, place, or thing the odd one out. We will accept your answer if it makes sense and it is not terrible.

6) Miley Cyrus, *Ariana Grande*, Demi Lovato, Selena Gomez

7) Beryllium, Sodium, Zinc, *Iodine*

8) John F Kennedy, Ulysses S. Grant, *Millard Fillmore*, James K. Polk

9) *Vision*, Iron Man, Spiderman, Hulk

10) Chinook, *Persian*, Pumi, Cane Corso

link:../../../index.html[Click here to return to the main site]
